version: '3'
services:
  node1:
    build: .
    environment:
      - PORT=8080
      - NODE_ENV=development
      - LOG_LEVEL=info
    ports:
      - "8080:8080"
      - "9229:9229"
    command: "npm start"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - uploads:/usr/src/app/uploads
      - logs:/usr/src/app/logs
      - c:\\Users\\manic\\exercise\\express-docker\\dist:/usr/src/app
      - c:\\Users\\manic\\exercise\\express-docker\\package.json:/usr/src/app/package.json
  nginx:
    build:
      context: ./
      dockerfile: nginx-alpine
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]

  redis:
    image: redis:4.0.11-alpine

  arangodb:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - "dbdata:/var/lib/arangodb3"

volumes:
  dbdata:
  node_modules:
  uploads:
  logs: